roads = shaperead('boston_roads.shp'); 

   
worldFile = 'myboston.jgw'; 
img = imread('myboston3.jpg'); 
R = worldfileread(worldFile); 

geoshow(img, R); 
title('Boston roads (geographic)'); 

[adjMatrix, startEndList, startEndListGeo, roadCount] = shpToGeoEucAdj(roads);

startIndex = 500;
endIndex = 2000;

[closedList] = ...
aStarConnectedFinder(...
adjMatrix, ...
startEndList,...
startEndListGeo,...
roadCount,...
startIndex,...
endIndex...
);
